# Generated by Django 5.0.6 on 2024-06-05 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partapp', '0002_ordermodel_city_ordermodel_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='email',
        ),
    ]
