# Generated by Django 5.0.6 on 2024-06-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partapp', '0003_remove_ordermodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodmodel',
            name='delivery',
        ),
    ]
