import { Inter, Roboto } from 'next/font/google';
import './globals.scss';
import { LayoutClient } from '@/components/layout/LayoutClient';

const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto({ subsets: ['latin'], weight: ['100', '300', '400', '500', '700', '900'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
